/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessControlState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessControlConfig"];
        put: operations["putAccessControlConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewAccessControlConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applyAccessControlConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessControlInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessControlAliases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccessControlPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessControlPeer: {
            name: string;
            ipv4Address: string;
            raw: {
                [key: string]: unknown;
            };
        };
        AccessControlServiceEntry: {
            protocol: string;
            port: number | string;
        } & {
            [key: string]: unknown;
        };
        AccessControlAliasCatalog: {
            groups: {
                [key: string]: string[];
            };
            hosts: {
                [key: string]: string[];
            };
            services: {
                [key: string]: components["schemas"]["AccessControlServiceEntry"][];
            };
        };
        AccessControlRule: {
            source?: string | string[];
            source_group?: string | string[];
            destination?: string | string[];
            destination_group?: string | string[];
            service?: string | string[];
            protocol?: string;
            port?: number | string;
            action: string;
            comment?: string;
        } & {
            [key: string]: unknown;
        };
        AccessControlCompiledState: {
            iptables: string[][];
            ipsets: {
                name: string;
                members: string[];
            }[];
        };
        AccessControlInventory: {
            backend: string;
            policyPath: string;
            aliasesPath: string;
            peers: components["schemas"]["AccessControlPeer"][];
            aliases: components["schemas"]["AccessControlAliasCatalog"];
        };
        AccessControlState: components["schemas"]["AccessControlInventory"] & {
            peerMap: {
                [key: string]: string;
            };
            rules: components["schemas"]["AccessControlRule"][];
            compiled: components["schemas"]["AccessControlCompiledState"];
        };
        AccessControlConfigDraft: {
            aliases: components["schemas"]["AccessControlAliasCatalog"];
            rules: components["schemas"]["AccessControlRule"][];
        };
        AccessControlConfigDocument: components["schemas"]["AccessControlConfigDraft"] & {
            policyPath: string;
            aliasesPath: string;
        };
        AccessControlMutationResult: {
            state: components["schemas"]["AccessControlState"];
            persisted: boolean;
            applied: boolean;
        };
        AccessControlAliasesResponse: {
            aliases: components["schemas"]["AccessControlAliasCatalog"];
        };
        AccessControlPoliciesResponse: {
            rules: components["schemas"]["AccessControlRule"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getAccessControlState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full access-control snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlState"];
                };
            };
        };
    };
    getAccessControlConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current aliases and policies document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlConfigDocument"];
                };
            };
        };
    };
    putAccessControlConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessControlConfigDraft"];
            };
        };
        responses: {
            /** @description Persisted aliases and policies without applying firewall changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlMutationResult"];
                };
            };
        };
    };
    previewAccessControlConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessControlConfigDraft"];
            };
        };
        responses: {
            /** @description Preview compiled state for an in-memory draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlMutationResult"];
                };
            };
        };
    };
    applyAccessControlConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessControlConfigDraft"];
            };
        };
        responses: {
            /** @description Persisted aliases and policies and applied compiled firewall rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlMutationResult"];
                };
            };
        };
    };
    getAccessControlInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Peer inventory and alias catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlInventory"];
                };
            };
        };
    };
    getAccessControlAliases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alias catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlAliasesResponse"];
                };
            };
        };
    };
    getAccessControlPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessControlPoliciesResponse"];
                };
            };
        };
    };
}
