services:
  application:
    build:
      context: .
    container_name: app-${SERVICE}
    environment:
      APP_SHELL_CONFIG_PATH: /config/app-shell.config.json
    volumes:
      - ${HOME_LAB_DIR:-.}/app-shell.config.json:/config/app-shell.config.json:ro
    ports:
      - "0.0.0.0:${SERVICEPORT}:3000/tcp"
    restart: unless-stopped
