services:
  # Portainer
  application:
    image: ${IMAGE_URL}
    container_name: app-${SERVICE}

    environment:
      - TZ=${TZ}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME_LAB_DIR:-.}/data:/data

    ports:
      - "0.0.0.0:${SERVICEPORT}:9000/tcp"

    networks:
      default: {}
      homelab: {}

    restart: unless-stopped

networks:
  default:
    name: portainer_internal
  homelab:
    external: true
